sudo: required

# Used for semver and parsing package.json
language: node_js
node_js:
  - "node"

services:
  - docker

env:
  global:
    # Docker Hub cannot handle uppercase characters in repository names. Fix it
    # with a bashism as Travis CI cannot handle quoting within command
    # substitution.
    - LOWERCASE_REPO_SLUG="${TRAVIS_REPO_SLUG,,}"
    - DOCKER_LOCAL="${LOWERCASE_REPO_SLUG}:${TRAVIS_COMMIT}"
    - DOCKER_MASTER="${LOWERCASE_REPO_SLUG}:latest"
    - DOCKER_GIT_TAG="${LOWERCASE_REPO_SLUG}:${TRAVIS_TAG}"

before_install:
  - docker --version
  - echo "ENV GIT_COMMIT ${TRAVIS_COMMIT}" >> Dockerfile
  - docker build --tag "${DOCKER_LOCAL}" .

script:
  - if [ -z ${TRAVIS_TAG+foo} ]; then
      package_version="$(node -p "require('./package.json').version")"
      if [ "${TRAVIS_TAG}" != "${package_version}" ]; then
        echo "TRAVIS_TAG ${TRAVIS_TAG} differs from \"version\" ${package_version} in package.json" 1>&2
        exit 1
      fi
      semver "${TRAVIS_TAG}" > /dev/null
      if [ "$?" -ne 0 ]; then
        echo "TRAVIS_TAG ${TRAVIS_TAG} does not follow semver" 1>&2
        exit 1
      fi
    else
      echo "TRAVIS_TAG was unset"
      echo 'Value of $([ -z ${TRAVIS_TAG+foo} ]):'"$([ -z ${TRAVIS_TAG+foo} ])"
      echo 'Value of $([ -z ${TRAVIS_TAG} ]):'"$([ -z ${TRAVIS_TAG} ])"
    fi
  - docker run --rm "${DOCKER_LOCAL}" yarn eslint
  - docker run --rm "${DOCKER_LOCAL}" yarn test

deploy:
  - provider: script
    script: sh ./.travis/docker_login_tag_push "${DOCKER_LOCAL}" "${DOCKER_MASTER}"
    on:
      branch: master
  - provider: script
    script: sh ./.travis/docker_login_tag_semver_push "${DOCKER_LOCAL}" "${LOWERCASE_REPO_SLUG}" "${TRAVIS_TAG}"
    on:
      tags: true
      all_branches: true
